In [27]:
import pandas as pd
import csv
import matplotlib.pyplot as plt
from datetime import datetime
import numpy as np
import os

In [72]:
input_dir = 'F:/Education/NSU/CSE/CSE499/Implementation/Dataset/combined_output.csv'
x_axis_dir = 'F:/Education/NSU/CSE/CSE499/Implementation/column1.csv'
df1 = pd.read_csv(input_dir, header=None, low_memory=False)
df2 = pd.read_csv(x_axis_dir)

In [73]:
x_axis = df2.values.flatten()
x_axis

array([16.   , 16.004, 16.008, ..., 19.992, 19.996, 20.   ])

In [36]:
output_dir = "F:/Education/NSU/CSE/CSE499/Implementation/Dataset/plots"
os.makedirs(output_dir, exist_ok=True)

In [64]:
# Indices for line1 and line2
line1_cols = list(range(26, 2028, 2))  # even columns
line2_cols = list(range(27, 2028, 2))  # odd columns
#line1_cols
line2_cols

[27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99,
 101,
 103,
 105,
 107,
 109,
 111,
 113,
 115,
 117,
 119,
 121,
 123,
 125,
 127,
 129,
 131,
 133,
 135,
 137,
 139,
 141,
 143,
 145,
 147,
 149,
 151,
 153,
 155,
 157,
 159,
 161,
 163,
 165,
 167,
 169,
 171,
 173,
 175,
 177,
 179,
 181,
 183,
 185,
 187,
 189,
 191,
 193,
 195,
 197,
 199,
 201,
 203,
 205,
 207,
 209,
 211,
 213,
 215,
 217,
 219,
 221,
 223,
 225,
 227,
 229,
 231,
 233,
 235,
 237,
 239,
 241,
 243,
 245,
 247,
 249,
 251,
 253,
 255,
 257,
 259,
 261,
 263,
 265,
 267,
 269,
 271,
 273,
 275,
 277,
 279,
 281,
 283,
 285,
 287,
 289,
 291,
 293,
 295,
 297,
 299,
 301,
 303,
 305,
 307,
 309,
 311,
 313,
 315,
 317,
 319,
 321,
 323,
 325,
 327,
 329,
 331,
 333,
 335,
 337,
 339,
 341,
 343,
 345,
 347,
 349,
 351,
 353,
 355,
 357,
 359,
 361,
 363,
 365,
 367,
 369,
 371,

In [65]:
# Sanity check (should be 1001 each)
assert len(line1_cols) == 1001 and len(line2_cols) == 1001

In [77]:
#lOOP

for i in range(len(df1)-1):
    line1 = df1.iloc[i+1, line1_cols].values.astype(float)
    line2 = df1.iloc[i+1, line2_cols].values.astype(float)
    print(line2)

    plt.figure(figsize=(10, 4))
    plt.plot(x_axis, line1, label="Real Line", color='blue')
    plt.plot(x_axis, line2, label="Imaginary Line", color='red', linestyle='--')
    plt.title(f"Graph {i+1}")
    plt.xlabel("Frequency (GHz)")
    plt.ylabel("Reflection Coefficient")
    plt.ylim(-1, 1)  # <- Set Y-axis range
    plt.legend()
    plt.grid(True)

    # Save the figure
    plt.savefig(f"{output_dir}/graph_{i+1}.png")
    plt.close()

print("✅ All graphs with interleaved lines have been saved.")

[-0.00634024 -0.00854204 -0.01075196 ... -0.12263833 -0.11701839
 -0.1115497 ]
[0.04721127 0.04504932 0.04288445 ... 0.65616052 0.6581163  0.66003192]
[ 0.33186509  0.3308472   0.32982714 ... -0.41267687 -0.41594207
 -0.41911962]
[ 0.14312465  0.14188806  0.14074362 ... -0.46586683 -0.46676428
 -0.46764443]
[-0.344288   -0.3417669  -0.33906856 ... -0.69363635 -0.69485186
 -0.69606437]
[ 0.19443977  0.19265498  0.19080453 ... -0.38914291 -0.3873643
 -0.3856089 ]
[-0.15214468 -0.15506551 -0.15798824 ... -0.68142863 -0.68346634
 -0.68546701]
[0.17905562 0.17648551 0.17391391 ... 0.04592476 0.04350282 0.04108794]
[ 0.07405519  0.07147491  0.06888717 ... -0.22432943 -0.22663771
 -0.22893742]
[-0.15132913 -0.15388917 -0.15643594 ... -0.25574967 -0.26059966
 -0.26539503]
[ 0.15160184  0.16287911  0.17394336 ... -0.56584306 -0.56753628
 -0.56921961]
[-0.00074352  0.00341339  0.00769354 ... -0.35577476 -0.35830042
 -0.36081505]
[0.05670976 0.05527061 0.05383063 ... 0.04939427 0.04647192 0.04355